Repository YuriSilenok/self-checking, pull requests merged in 2021-09, with the labels that each got.

#63 Запрос на проверку ветки issue-15
  static/css/main.css
  templates/discipline.html
  templates/solving.html
  templates/student_task.html
Labels: v0.1, Список дисциплин, Мои задания, Ожидает проверки, Верстка

#57 Верстка страницы "Список дисциплин"
  static/css/main.css
  templates/discipline.html
  templates/solving.html
Labels: v0.1, Список дисциплин

#64 BE Списка задач студента
  templates/discipline.html
  templates/header.html
  templates/student_task.html
Labels: v0.1, Мои задания, Заголовок, BE

#68 Верстка "Список требований"
  static/css/main.css
  templates/requirement.html
Labels: v0.1, Список требований

#69 Верстка "Загрузка решения на проверку".
  static/css/main.css
  templates/student_task_id.html
Labels: v0.1, Загрузить решение
